blank_issues_enabled: false
contact_links:
  - name: ğŸœ android-libraries repo
    url: https://github.com/MuntashirAkon/android-libraries
    about: Please send requests for new trackers and libraries to this repository.
  - name: ğŸ“— App Manager Docs
    url: https://muntashirakon.github.io/AppManager/
    about: Please read documentation carefully before submitting issue
